[package]
name = "rust-newsletter-api"
version = "0.1.0"
edition = "2024"

[lib]
path="src/lib.rs"

[[bin]]
path="src/main.rs"
name="rust_newsletter_api"

[dependencies]
actix-web = "4.14.0"
reqwest = "0.13.4"
serde = { version = "1.0.229", features = ["derive"] }
sqlx = { version = "0.9.0", default-features = false, features = ["runtime-tokio", "tls-rustls-ring-webpki", "macros", "postgres", "uuid", "chrono", "migrate"] }
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.26.0", features = ["v4"] }

